// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIiFaIyKa2KaUR0Qg8QwNZdu_wKq-gOaQ',
    appId: '1:800745898751:web:24f4eee8d902eceb3442ca',
    messagingSenderId: '800745898751',
    projectId: 'rush-poc',
    authDomain: 'rush-poc.firebaseapp.com',
    storageBucket: 'rush-poc.appspot.com',
    measurementId: 'G-THDQH7D34S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIgKMaJsvjhU474EqbT_5nXq7cIzHFF54',
    appId: '1:800745898751:android:76479f2d6108f5273442ca',
    messagingSenderId: '800745898751',
    projectId: 'rush-poc',
    storageBucket: 'rush-poc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEMJtCjoXp64h6YnnHJEwIO_liddTP4lg',
    appId: '1:800745898751:ios:4466cea6cc1aa0143442ca',
    messagingSenderId: '800745898751',
    projectId: 'rush-poc',
    storageBucket: 'rush-poc.appspot.com',
    iosClientId: '800745898751-umaj1svufdigo9nubs3glttfir2elr1e.apps.googleusercontent.com',
    iosBundleId: 'com.exaple.app',
  );
}
